### PR TITLE
Added EXTRA_NAXSI_RULES environment option

### PR DESCRIPTION
**Pull request by lewismarshall**
When there are only a couple of extra rules required for an application, this feature allows them to be easily added.

### CODE REVIEW

**Comment by lewismarshall** [comment]
LGTM if you like - needed to add this for file uploads for checking... @vaijab @gambol99 @jon-shanks @allandegnan

**Comment by lewismarshall** [comment]
@PurpleBooth @jon-shanks @gambol99

**Comment by PurpleBooth** [comment]
LGTM

**Comment by jon-shanks** [comment]
LGTM

**Pull request merged**
