### PR TITLE
Http to https redirect

### PR DESCRIPTION
**Pull request by lewismarshall**
Implemented. Will redirect http to https on same host. Added HTTPS_PORT variable (for testing) and updated tests.

Includes #20 and #18 (until merged).

### CODE REVIEW

**Comment by lewismarshall** [comment]
Can be tested with v0.4.0-rc1

**Comment by jon-shanks** [comment]
LGTM

**Comment by lewismarshall** [comment]
This is the only one left relevant @mikeyhu @gambol99

**Comment by mikeyhu** [comment]
Looks good to me

**Pull request merged**
