### PR TITLE
Client certs

### PR DESCRIPTION
**Pull request by lewismarshall**
Can now add client ca and require client certs per location. Still need to test successful connection....

### CODE REVIEW

**Comment by lewismarshall** [comment]
Fixes #17 
Fixes #16

**Comment by lewismarshall** [comment]
Added travis tests to properly regression test this - working for multi location and client certs... Any chance of an LGTM or two? @PurpleBooth @jon-shanks

**Comment by PurpleBooth** [comment]
Looks good!

**Comment by jon-shanks** [comment]
LGTM though it would be nice to have example nginx output to the examples you are giving on using the service. Sometimes it's easier to see as examples input and what the output is going to be, (even if you dont have to worry about it as you're taking away the need) just easy to visualise what bits do what

**Pull request merged**
